# Generated by Django 4.2.2 on 2023-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
    ]
